import type { Transaction } from "@/lib/types";
import {
  ShoppingBag,
  Utensils,
  GraduationCap,
  Briefcase,
  Film,
} from "lucide-react";

export const mockTransactions: Transaction[] = [
  {
    id: "1",
    name: "Campus Bookstore",
    category: "Education",
    amount: 1250.0,
    type: "expense",
    date: "2024-07-28",
    icon: GraduationCap,
    mode: "Card",
  },
  {
    id: "2",
    name: "Part-time Job",
    category: "Salary",
    amount: 15000.0,
    type: "income",
    date: "2024-07-27",
    icon: Briefcase,
    mode: "UPI",
  },
  {
    id: "3",
    name: "The Eatery",
    category: "Food",
    amount: 350.5,
    type: "expense",
    date: "2024-07-27",
    icon: Utensils,
    mode: "UPI",
  },
  {
    id: "4",
    name: "Movie Night",
    category: "Entertainment",
    amount: 500.0,
    type: "expense",
    date: "2024-07-26",
    icon: Film,
    mode: "Cash",
  },
  {
    id: "5",
    name: "Zara",
    category: "Shopping",
    amount: 2500.0,
    type: "expense",
    date: "2024-07-25",
    icon: ShoppingBag,
    mode: "Card",
  },
  {
    id: "6",
    name: "Scholarship",
    category: "Grant",
    amount: 25000.0,
    type: "income",
    date: "2024-07-25",
    icon: GraduationCap,
    mode: "UPI",
  },
];
