import type { Transaction } from "@/lib/types";
import {
  ShoppingBag,
  Utensils,
  GraduationCap,
  Briefcase,
  Film,
  PiggyBank,
} from "lucide-react";

export const mockTransactions: Transaction[] = [
    {
    id: "7",
    name: "Internship Stipend",
    category: "Salary",
    amount: 20000.0,
    type: "income",
    date: "2024-08-01",
    icon: Briefcase,
    mode: "UPI",
  },
  {
    id: "8",
    name: "Emergency Fund Deposit",
    category: "Savings",
    amount: 1500.0,
    type: "investment",
    date: "2024-07-30",
    icon: PiggyBank,
    mode: "UPI",
  },
  {
    id: "9",
    name: "University Cafe",
    category: "Food",
    amount: 450.0,
    type: "expense",
    date: "2024-07-29",
    icon: Utensils,
    mode: "Card",
  },
  {
    id: "1",
    name: "Campus Bookstore",
    category: "Education",
    amount: 1250.0,
    type: "expense",
    date: "2024-07-28",
    icon: GraduationCap,
    mode: "Card",
  },
  {
    id: "2",
    name: "Part-time Job",
    category: "Salary",
    amount: 15000.0,
    type: "income",
    date: "2024-07-27",
    icon: Briefcase,
    mode: "UPI",
  },
  {
    id: "3",
    name: "The Eatery",
    category: "Food",
    amount: 350.5,
    type: "expense",
    date: "2024-07-27",
    icon: Utensils,
    mode: "UPI",
  },
  {
    id: "4",
    name: "Movie Night",
    category: "Entertainment",
    amount: 500.0,
    type: "expense",
    date: "2024-07-26",
    icon: Film,
    mode: "Cash",
  },
  {
    id: "5",
    name: "Zara",
    category: "Shopping",
    amount: 2500.0,
    type: "expense",
    date: "2024-07-25",
    icon: ShoppingBag,
    mode: "Card",
  },
  {
    id: "6",
    name: "Scholarship",
    category: "Grant",
    amount: 25000.0,
    type: "income",
    date: "2024-07-25",
    icon: GraduationCap,
    mode: "UPI",
  },
];
